version: '3'

networks:
   mgmt:
      driver: bridge
      enable_ipv6: true
      ipam:
         config:
            - subnet: "${IP6}d0c:0:1/96"
              gateway: "${IP6}d0c:0:1"

services:
   membershipldap:
      image: osixia/openldap
      container_name: membershipldap
      networks:
         mgmt:
      environment:
         - LDAP_ADMIN_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - LDAP_DOMAIN=${ORGANIZATION_URL}
         - LDAP_ORGANISATION=${ORGANIZATION_URL}
         - LDAP_TLS=false
      volumes:
         - /data/slapd/membershipldap/database:/var/lib/ldap
         - /data/slapd/membershipldap/config:/etc/ldap/slapd.d

   membershipldapbackup:
      image: osixia/openldap-backup
      container_name: membershipldapbackup
      networks:
         mgmt:
      environment:
         - LDAP_BACKUP_CONFIG_CRON_EXP="0 4 * * *"
         - LDAP_BACKUP_DATA_CRON_EXP="0 4 * * *"
      volumes_from:
         - membershipldap
      volumes:
         - /data/openldap/membershipldap/backup:/data/backup

   pgsqlapi:
      image: cloudcix/pgsqlapi:latest
      container_name: pgsqlapi
      networks:
         mgmt:
      environment:
         - POSTGRES_PASSWORD=${PGSQLAPI_PASSWORD}
      volumes:
         - /var/lib/pgsqlapi:/var/lib/postgresql/data/
      
   pgsqltotp:
      image: cloudcix/pgsqltotp:latest
      container_name: pgsqltotp
      networks:
         mgmt:
      environment:
         - POSTGRES_PASSWORD=${PGSQLTOTP_PASSWORD}
      volumes:
         - /var/lib/pgsqltotp:/var/lib/postgresql/data/

   membership:
      image: cloudcix/membership:latest
      container_name: membership
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:1"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
         - membershipldap

   otp:
      image: cloudcix/otp:latest
      container_name: otp
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQLTOTP_PASSWORD=${PGSQLTOTP_PASSWORD}
         - PGSQLTOTP_USER=${PGSQLTOTP_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:2"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqltotp
         
   user_expiration_cron:
      image: cloudcix/membershipcron:latest
      container_name: user_expiration_cron
      networks:
         mgmt:
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      command: ['user_expiration_reminders']
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa

   iaas:
      image: cloudcix/iaas:latest
      container_name: iaas
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:3"
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
            
   appmanager:
      image: cloudcix/appmanager:latest
      container_name: appmanager
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:4"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   cop:
      image: cloudcix/cop:latest
      container_name: cop
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_ID_MEMBER=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:5002:4"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/app_framework/system_conf/public-key.rsa
         - cop_static_content:/static
      restart: on-failure
      
   apachedscop:
      image: tgbyte/apacheds:latest
      container_name: apachedscop
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:5002:2"

   pgadmincop:
      image: dpage/pgadmin4
      container_name: pgadmincop
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:5002:1"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMINCOP_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMINCOP_PASSWORD}
      depends_on:
         - pgsqlapi
         - pgsqltotp
 
   seed_pgsql:
      image: cloudcix/seed:latest
      container_name: seed_pgsql
      networks:
         mgmt:
      environment:
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
      restart: on-failure
      depends_on:
         - appmanager
         - iaas
         - membership
         - membershipldap
         - otp
         - pgsqlapi

   jaeger:
      image: jaegertracing/jaeger-agent:latest
      container_name: jaeger-agent
      command: ["--reporter.grpc.host-port=collector.${MAP_NAME}.${MAP_ORGANIZATION_URL}:14250"]
      networks:
         mgmt:
      restart: on-failure

   # Pit - Icarus metric gatherer
   pit:
      image: cloudcix/pit:latest
      container_name: pit
      environment:
         ICARUS_EMAIL: ${CLOUDCIX_API_USERNAME}
         ICARUS_PASSWORD: ${CLOUDCIX_API_PASSWORD}
         ICARUS_API_KEY: ${CLOUDCIX_API_KEY}
         ICARUS_API_URL: ${POD_NAME}.${ORGANIZATION_URL}
      network_mode: "host"
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:50003"]
         interval: 10s
         timeout: 5s
         retries: 5
      depends_on:
         - membership
         - iaas
         - nginxcop

   nginxcop:
      image: nginx:1.19.2-alpine
      container_name: nginxcop
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:a"
      environment:
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - POD_NAME=${POD_NAME}
         - PORTAL_NAME=${PORTAL_NAME}
      ports:
         - "${PMS4}:443:443"
         - "${PMS5}:443:443"
      volumes:
         - ./templates/cop:/etc/nginx/templates
         - /etc/nginx/certs:/etc/nginx/certs
         - cop_static_content:/static
      depends_on:
         - membership
         - otp
         - iaas
         - appmanager
         - cop

volumes:
   cop_static_content:
