version: '3'

networks:
   mgmt:
      driver: bridge
      enable_ipv6: true
      ipam:
         config:
            - subnet: "${DOCKER_MGMT_IP6}1/64"
              gateway: "${DOCKER_MGMT_IP6}1"

services:
   apachedscop:
      image: tgbyte/apacheds:latest
      container_name: apachedscop
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}5002:2"

   appmanager:
      image: cloudcix/appmanager:latest
      container_name: appmanager
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:4"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   circuit:
      image: cloudcix/circuit:latest
      container_name: circuit
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:11"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   cop:
      image: cloudcix/cop:latest
      container_name: cop
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_ID_MEMBER=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}5002:4"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/app_framework/system_conf/public-key.rsa
         - cop_static_content:/static
      restart: on-failure

   financial:
      image: cloudcix/financial:latest
      container_name: financial
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:6"
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
      
   iaas:
      image: cloudcix/iaas:latest
      container_name: iaas
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:3"
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
        
   jaeger:
      image: jaegertracing/jaeger-agent:latest
      container_name: jaeger-agent
      command: ["--reporter.grpc.host-port=collector.${PAM_NAME}.${PAM_ORGANIZATION_URL}:14250"]
      networks:
         mgmt:
      restart: on-failure
   
   legacyapi:
      image: cloudcix/legacyapi:latest
      container_name: legacyapi
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:12"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
         - leagacyapi_media_content:/media
         - leagacyapi_private_media_content:/private_media
         - leagacyapi_static_content:/static
      restart: on-failure
      depends_on:
         - pgsqlapi

   membership:
      image: cloudcix/membership:latest
      container_name: membership
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:1"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
         - membershipldap

   membershipldap:
      image: osixia/openldap
      container_name: membershipldap
      networks:
         mgmt:
      environment:
         - LDAP_ADMIN_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - LDAP_DOMAIN=${ORGANIZATION_URL}
         - LDAP_ORGANISATION=${ORGANIZATION_URL}
         - LDAP_TLS=false
      volumes:
         - /data/slapd/membershipldap/database:/var/lib/ldap
         - /data/slapd/membershipldap/config:/etc/ldap/slapd.d

   membershipldapbackup:
      image: osixia/openldap-backup
      container_name: membershipldapbackup
      networks:
         mgmt:
      environment:
         - LDAP_BACKUP_CONFIG_CRON_EXP="0 4 * * *"
         - LDAP_BACKUP_DATA_CRON_EXP="0 4 * * *"
      volumes_from:
         - membershipldap
      volumes:
         - /data/openldap/membershipldap/backup:/data/backup

   nginxcop:
      image: nginx:1.19.2-alpine
      container_name: nginxcop
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:a"
      environment:
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - POD_NAME=${POD_NAME}
         - PORTAL_NAME=${PORTAL_NAME}
      ports:
         - "${PMS4}:443:443"
         - "${PMS5}:443:443"
      volumes:
         - ./templates/cop:/etc/nginx/templates
         - /etc/nginx/certs:/etc/nginx/certs
         - cop_static_content:/app_framework/static
         - leagacyapi_media_content:/application_framework/media
         - leagacyapi_static_content:/application_framework/static
      depends_on:
         - appmanager
         - circuit
         - financial
         - iaas
         - legacyapi
         - membership
         - otp
         - scheduler
         - support
         - training

   otp:
      image: cloudcix/otp:latest
      container_name: otp
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - PGSQLTOTP_PASSWORD=${PGSQLTOTP_PASSWORD}
         - PGSQLTOTP_USER=${PGSQLTOTP_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:2"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqltotp
         
   pgadmincop:
      image: dpage/pgadmin4
      container_name: pgadmincop
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}5002:1"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMINCOP_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMINCOP_PASSWORD}
      depends_on:
         - pgsqlapi
         - pgsqltotp
 
   pgsqlapi:
      image: cloudcix/pgsqlapi:latest
      container_name: pgsqlapi
      networks:
         mgmt:
      environment:
         - POSTGRES_PASSWORD=${PGSQLAPI_PASSWORD}
      volumes:
         - /var/lib/pgsqlapi:/var/lib/postgresql/data/
      
   pgsqltotp:
      image: cloudcix/pgsqltotp:latest
      container_name: pgsqltotp
      networks:
         mgmt:
      environment:
         - POSTGRES_PASSWORD=${PGSQLTOTP_PASSWORD}
      volumes:
         - /var/lib/pgsqltotp:/var/lib/postgresql/data/

   pit:
      image: cloudcix/pit:latest
      container_name: pit
      environment:
         - ICARUS_EMAIL=${CLOUDCIX_API_USERNAME}
         - ICARUS_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - ICARUS_API_KEY=${CLOUDCIX_API_KEY}
         - ICARUS_API_URL=${POD_NAME}.${ORGANIZATION_URL}
      network_mode: "host"
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:50003"]
         interval: 10s
         timeout: 5s
         retries: 5
      depends_on:
         - membership
         - iaas
         - nginxcop

   scheduler:
      image: cloudcix/scheduler:latest
      container_name: scheduler
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:7"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   seed_pgsql:
      image: cloudcix/seed:latest
      container_name: seed_pgsql
      networks:
         mgmt:
      environment:
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
      restart: on-failure
      depends_on:
         - appmanager
         - iaas
         - membership
         - membershipldap
         - otp
         - pgsqlapi

   support:
      image: cloudcix/support:latest
      container_name: support
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:10"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   training:
      image: cloudcix/training:latest
      container_name: training
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:5"
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   user_expiration_cron:
      image: cloudcix/membershipcron:latest
      container_name: user_expiration_cron
      networks:
         mgmt:
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      command: ['user_expiration_reminders']
      volumes:
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa_${POD_NUMBER}.pub:/application_framework/public-key.rsa

volumes:
   cop_static_content:
   leagacyapi_media_content:
   leagacyapi_private_media_content:
   leagacyapi_static_content:
