version: '3'
services:
  membershipldap:
    image: osixia/openldap
    container_name: membershipldap

  membership:
    image: cloudcix/membership:0.3
    container_name: membership
    environment:
       - PGSQL_PASSWORD=${POSTGRES_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION=${ORGANIZATION}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - LDAP_DOMAIN_CONTROLLER=${LDAP_DOMAIN_CONTROLLER}
       - LDAP_PASSWORD=${LDAP_PASSWORD}
    ports:
        - "${IP6}4004:1:80:80"
        - "${IP6}4004:1:443:443"
    volumes:
       - /var/private.pem:/application_framework/private-key.rsa
       - /var/public.pem:/application_framework/public_key.rsa

  otp:
    image: cloudcix/otp:0.4
    container_name: otp
    environment:
       - PGSQL_PASSWORD=${POSTGRES_PASSWORD}
       - PGSQLTOTP_PASSWORD=${PGSQLTOTP_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION=${ORGANIZATION}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
    ports:
        - "${IP6}4004:2:80:80"
        - "${IP6}4004:2:443:443"
    volumes:
       - /var/public.pem:/application_framework/public_key.rsa
        
  user_expiration_cron:
    image: cloudcix/membershipcron:0.1
    container_name: user_expiration_cron
    environment:
       - PGSQL_PASSWORD=${POSTGRES_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION=${ORGANIZATION}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - LDAP_DOMAIN_CONTROLLER=${LDAP_DOMAIN_CONTROLLER}
       - LDAP_PASSWORD=${LDAP_PASSWORD}
    command: ['user_expiration_reminders']
    
  iaas:
    image: cloudcix/iaas:0.3
    container_name: iaas
    environment:
       - PGSQL_PASSWORD=${POSTGRES_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION=${ORGANIZATION}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
    ports:
        - "${IP6}4004:3:80:80"
        - "${IP6}4004:3:443:443"
    volumes:
       - /var/public.pem:/application_framework/public_key.rsa
        
  appmanager:
    image: cloudcix/appmanager:0.0
    container_name: appmanager
    environment:
       - PGSQL_PASSWORD=${POSTGRES_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION=${ORGANIZATION}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
    ports:
        - "${IP6}4004:4:80:80"
        - "${IP6}4004:4:443:443"
    volumes:
       - /var/public.pem:/application_framework/public_key.rsa
        
  pgsql:
    image: cloudcix/pgsql:0.0
    container_name: pgsql
    environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
       - /var/lib/pgsql:/var/lib/postgresql/data/
       
  pgsqltotp:
    image: cloudcix/pgsqltotp:0.0
    container_name: pgsqltotp
    environment:
       - POSTGRES_PASSWORD=${PGSQLTOTP_PASSWORD}
    volumes:
       - /var/lib/pgsqltotp:/var/lib/postgresql/data/

  cop:
    image: cloudcix/cop:0.0
    container_name: cop
    environment:
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION=${ORGANIZATION}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
    ports:
      - "${PMS5}:80:80"
      - "${PMS5}:443:443"
      - "${IP6}5002:3:80:80"
      - "${IP6}5002:3:443:443"
    volumes:
       - /var/public.pem:/application_framework/public_key.rsa
  
  apache:
     image: httpd:latest
     container_name: apache
     ports:
      - "${PMS4}:80:80"
      - "${PMS4}:443:443"
      
  apacheds:
      image: tgbyte/apacheds:latest
      container_name: apacheds
      ports:
        - "${PMS5}:10389:80"
        - "${IP6}5002:2:10389:10389"
        
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      ports:
        - "${PMS5}:5432:80"
        - "${IP6}5002:1:5432:80"
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@postgres
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

