version: '3'

networks:
  default:
    driver: bridge
  mgmt:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "${IP6}/64"
          gateway: "${IP6}1"

services:
  membershipldap:
    image: osixia/openldap
    container_name: membershipldap
    environment:
       - LDAP_ORGANISATION=${ORGANIZATION_URL}
       - LDAP_DOMAIN=${ORGANIZATION_URL}
       - LDAP_ADMIN_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
    volumes:
       - /data/slapd/membershipldap/database:/var/lib/ldap
       - /data/slapd/membershipldap/config:/etc/ldap/slapd.d
    networks:
      default:

  membershipldapbackup:
    image: osixia/openldap-backup
    container_name: membershipldapbackup
    volumes_from:
      - membershipldap
    volumes:
      - /data/openldap/membershipldap/backup:/data/backup
    networks:
      default:

  pgsqlapi:
    image: cloudcix/pgsqlapi:latest
    container_name: pgsqlapi
    environment:
       - POSTGRES_PASSWORD=${PGSQLAPI_PASSWORD}
    volumes:
       - /var/lib/pgsqlapi:/var/lib/postgresql/data/
    networks:
      default:
       
  pgsqltotp:
    image: cloudcix/pgsqltotp:latest
    container_name: pgsqltotp
    environment:
       - POSTGRES_PASSWORD=${PGSQLTOTP_PASSWORD}
    volumes:
       - /var/lib/pgsqltotp:/var/lib/postgresql/data/
    networks:
      default:

  membership:
    image: cloudcix/membership:latest
    container_name: membership
    environment:
       - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
       - PGSQL_USER=${PGSQLAPI_USER}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION_URL=${ORGANIZATION_URL}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - LDAP_DOMAIN_CONTROLLER=${MEMBERSHIPLDAP_DC}
       - LDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
       - SENTRY_URL=${SENTRY_URL}
       - PAM_NAME=${PAM_NAME}
       - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
       - SUPER_USER_IDS=${SUPER_USER_IDS}
       - EMAIL_HOST=${EMAIL_HOST}
       - EMAIL_HOST_USER=${EMAIL_HOST_USER}
       - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
       - EMAIL_PORT=${EMAIL_PORT}
       - RELEASE=stable
    networks:
      default:
      mgmt:
        ipv6_address: "${IP6}4004:1"
    volumes:
       - /var/private.pem:/application_framework/private-key.rsa
       - /var/public.pem:/application_framework/public-key.rsa
    restart: on-failure
    depends_on:
        - pgsqlapi
        - membershipldap

  otp:
    image: cloudcix/otp:latest
    container_name: otp
    environment:
       - PGSQLTOTP_USER=${PGSQLTOTP_USER}
       - PGSQLTOTP_PASSWORD=${PGSQLTOTP_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION_URL=${ORGANIZATION_URL}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - SENTRY_URL=${SENTRY_URL}
       - PAM_NAME=${PAM_NAME}
       - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
       - SUPER_USER_IDS=${SUPER_USER_IDS}
       - EMAIL_HOST=${EMAIL_HOST}
       - EMAIL_USER=${EMAIL_USER}
       - EMAIL_PASSWORD=${EMAIL_PASSWORD}
       - EMAIL_PORT=${EMAIL_PORT}
       - RELEASE=stable
    networks:
      default:
      mgmt:
        ipv6_address: "${IP6}4004:2"
    volumes:
       - /var/public.pem:/application_framework/public-key.rsa
    restart: on-failure
    depends_on:
        - pgsqltotp
        
  user_expiration_cron:
    image: cloudcix/membershipcron:latest
    container_name: user_expiration_cron
    environment:
       - PGSQL_USER=${PGSQLAPI_USER}
       - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION_URL=${ORGANIZATION_URL}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - LDAP_DOMAIN_CONTROLLER=${MEMBERSHIPLDAP_DC}
       - LDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
       - SENTRY_URL=${SENTRY_URL}
       - PAM_NAME=${PAM_NAME}
       - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
       - SUPER_USER_IDS=${SUPER_USER_IDS}
       - EMAIL_HOST=${EMAIL_HOST}
       - EMAIL_USER=${EMAIL_USER}
       - EMAIL_PASSWORD=${EMAIL_PASSWORD}
       - EMAIL_PORT=${EMAIL_PORT}
       - RELEASE=stable
    command: ['user_expiration_reminders']
    networks:
      default:
    
  iaas:
    image: cloudcix/iaas:latest
    container_name: iaas
    environment:
       - PGSQL_USER=${PGSQLAPI_USER}
       - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION_URL=${ORGANIZATION_URL}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - SENTRY_URL=${SENTRY_URL}
       - PAM_NAME=${PAM_NAME}
       - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
       - SUPER_USER_IDS=${SUPER_USER_IDS}
       - EMAIL_HOST=${EMAIL_HOST}
       - EMAIL_USER=${EMAIL_USER}
       - EMAIL_PASSWORD=${EMAIL_PASSWORD}
       - EMAIL_PORT=${EMAIL_PORT}
       - RELEASE=stable
    networks:
      default:
      mgmt:
        ipv6_address: "${IP6}4004:3"
    volumes:
       - /var/public.pem:/application_framework/public-key.rsa
    restart: on-failure
    depends_on:
        - pgsqlapi
        
  appmanager:
    image: cloudcix/appmanager:latest
    container_name: appmanager
    environment:
       - PGSQL_USER=${PGSQLAPI_USER}
       - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION_URL=${ORGANIZATION_URL}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - SENTRY_URL=${SENTRY_URL}
       - PAM_NAME=${PAM_NAME}
       - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
       - SUPER_USER_IDS=${SUPER_USER_IDS}
       - EMAIL_HOST=${EMAIL_HOST}
       - EMAIL_USER=${EMAIL_USER}
       - EMAIL_PASSWORD=${EMAIL_PASSWORD}
       - EMAIL_PORT=${EMAIL_PORT}
       - RELEASE=stable
    networks:
      default:
      mgmt:
        ipv6_address: "${IP6}4004:4"
    volumes:
       - /var/public.pem:/application_framework/public-key.rsa
    restart: on-failure
    depends_on:
        - pgsqlapi

  cop:
    image: cloudcix/cop:latest
    container_name: cop
    environment:
       - PGSQL_USER=${PGSQLAPI_USER}
       - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION_URL=${ORGANIZATION_URL}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - SENTRY_URL=${SENTRY_URL}
       - PAM_NAME=${PAM_NAME}
       - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
       - EMAIL_HOST=${EMAIL_HOST}
       - EMAIL_USER=${EMAIL_USER}
       - EMAIL_PASSWORD=${EMAIL_PASSWORD}
       - EMAIL_PORT=${EMAIL_PORT}  
    networks:
      default:
      mgmt:
        ipv6_address: "${IP6}5002:3"
    ports:
      - "${PMS5}:80:80"
      - "${PMS5}:443:443"
    volumes:
       - /var/public.pem:/app_framework/system_conf/public-key.rsa
  
  apache:
    image: cloudcix/apiproxy:latest
    container_name: apiproxy
    environment:
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - ORGANIZATION_URL=${ORGANIZATION_URL}
        - POD_NAME=${POD_NAME}
    ports:
        - "${PMS4}:80:80"
        - "${PMS4}:443:443"
    volumes:
       - type: volume
         source: letsencrypt
         target: /etc/letsencrypt
         volume: 
           nocopy: true
    networks:
      default:
      
  apachedscop:
    image: tgbyte/apacheds:latest
    container_name: apachedscop
    networks:
      default:
      mgmt:
        ipv6_address: "${IP6}5002:2"
        
  pgadmincop:
    image: dpage/pgadmin4
    container_name: pgadmincop
    networks:
      default:
      mgmt:
        ipv6_address: "${IP6}5002:1"
    ports:
      - "${PMS5}:5432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMINCOP_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMINCOP_PASSWORD}
    depends_on:
      - pgsqlapi
      - pgsqltotp
   
  seed_pgsql:
    image: cloudcix/seed:latest
    container_name: seed_pgsql
    environment:
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
       - LDAP_DOMAIN_CONTROLLER=${MEMBERSHIPLDAP_DC}
       - LDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
       - ORGANIZATION_URL=${ORGANIZATION_URL}
       - POD_NAME=${POD_NAME}
       - PGSQL_USER=${PGSQLAPI_USER}
       - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
    restart: on-failure
    depends_on:
        - pgsqlapi
        - membership
        - membershipldap
        - appmanager
        - iaas
        - otp
    networks:
      default:

volumes:
    letsencrypt:
