version: '3'

networks:
   mgmt:
      driver: bridge
      enable_ipv6: true
      ipam:
         config:
            - subnet: "${DOCKER_MGMT_IP6}1/64"
              gateway: "${DOCKER_MGMT_IP6}1"
   oob:
      driver: macvlan
      driver_opts:
         parent: ${OOB_INTERFACE}
      ipam:
         config:
            - subnet: "10.${pod_id}.0.0/16"
              ip_range: "10.${pod_id}.0.0/24"
              gateway: "10.${pod_id}.0.1"

services:
   # cop containers
   membershipldap:
      image: osixia/openldap
      container_name: membershipldap
      networks:
         mgmt:
      environment:
         - LDAP_ADMIN_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - LDAP_DOMAIN=${ORGANIZATION_URL}
         - LDAP_ORGANISATION=${ORGANIZATION_URL}
         - LDAP_TLS=false
      volumes:
         - /data/slapd/membershipldap/database:/var/lib/ldap
         - /data/slapd/membershipldap/config:/etc/ldap/slapd.d

   membershipldapbackup:
      image: osixia/openldap-backup
      container_name: membershipldapbackup
      networks:
         mgmt:
      environment:
         - LDAP_BACKUP_CONFIG_CRON_EXP="0 4 * * *"
         - LDAP_BACKUP_DATA_CRON_EXP="0 4 * * *"
      volumes_from:
         - membershipldap
      volumes:
         - /data/openldap/membershipldap/backup:/data/backup

   pgsqlapi:
      image: cloudcix/pgsqlapi:latest
      container_name: pgsqlapi
      networks:
         mgmt:
      environment:
         - POSTGRES_PASSWORD=${PGSQLAPI_PASSWORD}
      volumes:
         - /var/lib/pgsqlapi:/var/lib/postgresql/data/
      
   pgsqltotp:
      image: cloudcix/pgsqltotp:latest
      container_name: pgsqltotp
      networks:
         mgmt:
      environment:
         - POSTGRES_PASSWORD=${PGSQLTOTP_PASSWORD}
      volumes:
         - /var/lib/pgsqltotp:/var/lib/postgresql/data/

   membership:
      image: cloudcix/membership:latest
      container_name: membership
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:1"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
         - membershipldap

   otp:
      image: cloudcix/otp:latest
      container_name: otp
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - PGSQLTOTP_PASSWORD=${PGSQLTOTP_PASSWORD}
         - PGSQLTOTP_USER=${PGSQLTOTP_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:2"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqltotp
         
   user_expiration_cron:
      image: cloudcix/membershipcron:latest
      container_name: user_expiration_cron
      networks:
         mgmt:
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      command: ['user_expiration_reminders']
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa

   iaas:
      image: cloudcix/iaas:latest
      container_name: iaas
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:3"
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
            
   appmanager:
      image: cloudcix/appmanager:latest
      container_name: appmanager
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:4"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   support:
      image: cloudcix/support:latest
      container_name: support
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:10"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   cop:
      image: cloudcix/cop:latest
      container_name: cop
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_ID_MEMBER=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PAM_NAME=${PAM_NAME}
         - PAM_ORGANIZATION_URL=${PAM_ORGANIZATION_URL}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}5002:4"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/app_framework/system_conf/public-key.rsa
         - cop_static_content:/static
      restart: on-failure
      
   apachedscop:
      image: tgbyte/apacheds:latest
      container_name: apachedscop
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}5002:2"

   pgadmincop:
      image: dpage/pgadmin4
      container_name: pgadmincop
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}5002:1"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMINCOP_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMINCOP_PASSWORD}
      depends_on:
         - pgsqlapi
         - pgsqltotp
 
   seed_pgsql:
      image: cloudcix/seed:latest
      container_name: seed_pgsql
      networks:
         mgmt:
      environment:
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PGSQLAPI_USER=${PGSQLAPI_USER}
         - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
      restart: on-failure
      depends_on:
         - appmanager
         - iaas
         - membership
         - membershipldap
         - otp
         - pgsqlapi

   pit:
      image: cloudcix/pit:latest
      container_name: pit
      environment:
         - ICARUS_EMAIL=${CLOUDCIX_API_USERNAME}
         - ICARUS_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - ICARUS_API_KEY=${CLOUDCIX_API_KEY}
         - ICARUS_API_URL=${POD_NAME}.${ORGANIZATION_URL}
      network_mode: "host"
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:50003"]
         interval: 10s
         timeout: 5s
         retries: 5
      depends_on:
         - membership
         - iaas
         - nginxcop

   nginxcop:
      image: nginx:1.19.2-alpine
      container_name: nginxcop
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}4004:a"
      environment:
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - POD_NAME=${POD_NAME}
         - PORTAL_NAME=${PORTAL_NAME}
      ports:
         - "${PMS4}:443:443"
         - "${PMS5}:443:443"
      volumes:
         - ./templates/cop:/etc/nginx/templates
         - /etc/nginx/certs:/etc/nginx/certs
         - cop_static_content:/app_framework/static
      depends_on:
         - membership
         - otp
         - iaas
         - appmanager
         - cop
         - support

   # region containers
   robot:
      image: cloudcix/robot:latest
      container_name: robot
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}6001:1"
      environment:
         - COP_NAME=${COP_NAME}
         - COP_ORGANIZATION_URL=${COP_ORGANIZATION_URL}
         - COP_PORTAL=${COP_PORTAL}
         - EMAIL_HOST=${REGION_EMAIL_HOST}
         - EMAIL_PASSWORD=${REGION_EMAIL_PASSWORD}
         - EMAIL_PORT=${REGION_EMAIL_PORT}
         - EMAIL_USER=${REGION_EMAIL_USER}
         - NETWORK_PASSWORD=${NETWORK_PASSWORD}
         - PAM_NAME=${REGION_PAM_NAME}
         - PAM_ORGANIZATION_URL=${REGION_PAM_ORGANIZATION_URL}
         - POD_NAME=${POD_NAME}
         - PODNET_CPE=${PODNET_CPE}
         - ROUTER_PRIVATE_INTERFACE=${ROUTER_PRIVATE_INTERFACE}
         - ROUTER_PUBLIC_INTERFACE=${ROUTER_PUBLIC_INTERFACE}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - ROBOT_API_KEY=${ROBOT_API_KEY}
         - ROBOT_API_PASSWORD=${ROBOT_API_PASSWORD}
         - ROBOT_API_USERNAME=${ROBOT_API_USERNAME}
         - ROUTER_MGMT_IP=${ROUTER_MANAGEMENT_IP}
         - SEND_TO_FAIL=${SEND_TO_FAIL}
      volumes:
         - /home/administrator/celerybeat:/opt/robot/celerybeat
         - /home/administrator/.ssh/id_rsa_${pod_id}:/root/.ssh/id_rsa
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/root/.ssh/id_rsa.pub
      entrypoint: supervisord

   robotworker:
      image: cloudcix/robot:latest
      container_name: robotworker
      environment:
         - COP_NAME=${COP_NAME}
         - COP_ORGANIZATION_URL=${COP_ORGANIZATION_URL}
         - COP_PORTAL=${COP_PORTAL}
         - EMAIL_HOST=${REGION_EMAIL_HOST}
         - EMAIL_PASSWORD=${REGION_EMAIL_PASSWORD}
         - EMAIL_PORT=${REGION_EMAIL_PORT}
         - EMAIL_USER=${REGION_EMAIL_USER}
         - NETWORK_PASSWORD=${NETWORK_PASSWORD}
         - PAM_NAME=${REGION_PAM_NAME}
         - PAM_ORGANIZATION_URL=${REGION_PAM_ORGANIZATION_URL}
         - POD_NAME=${POD_NAME}
         - PODNET_CPE=${PODNET_CPE}
         - ROUTER_PRIVATE_INTERFACE=${ROUTER_PRIVATE_INTERFACE}
         - ROUTER_PUBLIC_INTERFACE=${ROUTER_PUBLIC_INTERFACE}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - ROBOT_API_KEY=${ROBOT_API_KEY}
         - ROBOT_API_PASSWORD=${ROBOT_API_PASSWORD}
         - ROBOT_API_USERNAME=${ROBOT_API_USERNAME}
         - ROUTER_MGMT_IP=${ROUTER_MANAGEMENT_IP}
         - SEND_TO_FAIL=${SEND_TO_FAIL}
      volumes:
         - /etc/cloudcix/robot:/mnt/images
         - /home/administrator/.ssh/id_rsa_${pod_id}:/root/.ssh/id_rsa
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/root/.ssh/id_rsa.pub
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}6001:2"
      entrypoint: celery -A celery_app -l info worker -Q celery -O fair -n ${POD_NAME} --concurrency 25

   rabbitmq:
      image: rabbitmq
      container_name: rabbitmqregion
      hostname: rabbitmq
      networks:
        mgmt:

   flower:
      image: mher/flower:0.9.5
      container_name: flowerregion
      networks:
         mgmt:
            ipv6_address: "${DOCKER_MGMT_IP6}6002:4"
      ports:
         - "${PMS6}:5555:5555"
      entrypoint: flower --port=5555 --broker=amqp://rabbitmq:5672/

volumes:
   # cop volumes
   cop_static_content:
