version: '3'

networks:
   pam:
      driver: bridge
   cop:
      driver: bridge
   mgmt:
      driver: bridge
      enable_ipv6: true
      ipam:
         config:
            - subnet: "${IP6}/80"
              gateway: "${IP6}ffff"
   oob:
      driver: macvlan
      driver_opts:
         parent: ${OOB_INTERFACE}
      ipam:
         config:
            - subnet: "10.${pod_id}.0.0/16"
              ip_range: "10.${pod_id}.0.0/24"
              gateway: "10.${pod_id}.0.1"

services:
# pam containers
   pgsqlpam:
      image: cloudcix/pgsqlpam:latest
      container_name: pgsqlpam
      networks:
         pam:
      environment:
            - POSTGRES_PASSWORD=${PGSQLPAM_PASSWORD}
      volumes:
            - /var/lib/pgsqlpam:/var/lib/postgresql/data/


   pgadminpam:
      image: dpage/pgadmin4
      container_name: pgadminpam
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.7"
      ports:
         - "${PMS3}:5432:80"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMINPAM_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMINPAM_PASSWORD}
      depends_on:
         - pgsqlpam

   pam:
      image: cloudcix/pam:latest
      container_name: pam
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.6"
      environment:
         - PGSQLPAM_PASSWORD=${PGSQLPAM_PASSWORD}
         - PGSQLPAM_USER=${PGSQLPAM_USER}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
      depends_on:
         - pgsqlpam
      restart: on-failure

   librenms:
      image: librenms/librenms
      container_name: librenms
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.4"
      environment:
         - DB_HOST=mysql
         - DB_NAME=${MYSQL_DATABASE}
         - DB_USER=${MYSQL_USER}
         - DB_PASSWORD=${MYSQL_PASSWORD}
      depends_on:
         - mysql

   mysql:
      image: mysql
      container_name: mysql
      networks:
         pam:
      ports:
         - "3306:3306"
      environment:
         - MYSQL_DATABASE=${MYSQL_DATABASE}
         - MYSQL_USER=${MYSQL_USER}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
         - "/etc/cloudcix/docker/radius/data:/var/lib/mysql"
         - "/etc/cloudcix/docker/radius/radius.sql:/docker-entrypoint-initdb.d/radius.sql"
      command: --default-authentication-plugin=mysql_native_password
      restart: always


   radius:
      image: 2stacks/freeradius
      container_name: radius
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.3"
      ports:
         - "1812-1813:1812-1813/udp"
      environment:
         - DB_NAME=${MYSQL_DATABASE}
         - DB_HOST=mysql
         - DB_USER=${MYSQL_USER}
         - DB_PASS=${MYSQL_PASSWORD}
         - RADIUS_KEY=${RADIUS_SECRET_KEY}
         - RAD_CLIENTS=10.0.0.0/8
      depends_on:
         - mysql
      links:
         - mysql
      restart: always

   mysql-workbench:
      image: linuxserver/mysql-workbench
      container_name: mysql-workbench
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.8"
      ports:
         - 3000:3000
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/Dublin
      cap_add:
         - IPC_LOCK
      restart: unless-stopped

   jumphost:
      image: cloudcix/jumphost:latest
      container_name: jumphost
      networks:
         oob:
            ipv4_address: "10.${pod_id}.0.5"
         mgmt:
            ipv6_address: "${IP6}3002:1"
      environment:
         - RESOLUTION=1280x720
         - USER=${JUMPHOST_USERNAME}
         - PASSWORD=${JUMPHOST_PASSWORD}
         - HTTP_PASSWORD=${JUMPHOST_HTTP_PASSWORD}
         - VNC_PASSWORD=${JUMPHOST_VNC_PASSWORD}
      restart: always

# cop containers
   membershipldap:
      image: osixia/openldap
      container_name: membershipldap
      networks:
         cop:
      environment:
         - LDAP_ORGANISATION=${ORGANIZATION_URL}
         - LDAP_DOMAIN=${ORGANIZATION_URL}
         - LDAP_ADMIN_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
      volumes:
         - /data/slapd/membershipldap/database:/var/lib/ldap
         - /data/slapd/membershipldap/config:/etc/ldap/slapd.d

   membershipldapbackup:
      image: osixia/openldap-backup
      container_name: membershipldapbackup
      networks:
         cop:
      environment:
         - LDAP_BACKUP_CONFIG_CRON_EXP="0 4 * * *"
         - LDAP_BACKUP_DATA_CRON_EXP="0 4 * * *"
      volumes_from:
         - membershipldap
      volumes:
         - /data/openldap/membershipldap/backup:/data/backup

   pgsqlapi:
      image: cloudcix/pgsqlapi:latest
      container_name: pgsqlapi
      networks:
         cop:
      environment:
         - POSTGRES_PASSWORD=${PGSQLAPI_PASSWORD}
      volumes:
         - /var/lib/pgsqlapi:/var/lib/postgresql/data/
      
   pgsqltotp:
      image: cloudcix/pgsqltotp:latest
      container_name: pgsqltotp
      networks:
         cop:
      environment:
         - POSTGRES_PASSWORD=${PGSQLTOTP_PASSWORD}
      volumes:
         - /var/lib/pgsqltotp:/var/lib/postgresql/data/

   membership:
      image: cloudcix/membership:latest
      container_name: membership
      environment:
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - POD_NAME=${POD_NAME}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - SENTRY_URL=${COP_SENTRY_URL}
         - PAM_NAME=${COP_PAM_NAME}
         - PAM_ORGANIZATION_URL=${COP_PAM_ORGANIZATION_URL}
         - SUPER_USER_IDS=${SUPER_USER_IDS}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_USER=${COP_EMAIL_USER}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - RELEASE=stable
      networks:
         cop:
         mgmt:
            ipv6_address: "${IP6}4004:1"
      volumes:
         - /home/administrator/.ssh/id_rsa:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
         - membershipldap

   otp:
      image: cloudcix/otp:latest
      container_name: otp
      environment:
         - PGSQLTOTP_USER=${PGSQLTOTP_USER}
         - PGSQLTOTP_PASSWORD=${PGSQLTOTP_PASSWORD}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - POD_NAME=${POD_NAME}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - SENTRY_URL=${COP_SENTRY_URL}
         - PAM_NAME=${COP_PAM_NAME}
         - PAM_ORGANIZATION_URL=${COP_PAM_ORGANIZATION_URL}
         - SUPER_USER_IDS=${SUPER_USER_IDS}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_USER=${COP_EMAIL_USER}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - RELEASE=stable
      networks:
         cop:
         mgmt:
            ipv6_address: "${IP6}4004:2"
      volumes:
         - /home/administrator/.ssh/id_rsa.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqltotp
         
   user_expiration_cron:
      image: cloudcix/membershipcron:latest
      container_name: user_expiration_cron
      environment:
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - POD_NAME=${POD_NAME}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - SENTRY_URL=${COP_SENTRY_URL}
         - PAM_NAME=${COP_PAM_NAME}
         - PAM_ORGANIZATION_URL=${COP_PAM_ORGANIZATION_URL}
         - SUPER_USER_IDS=${SUPER_USER_IDS}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_USER=${COP_EMAIL_USER}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - RELEASE=stable
      command: ['user_expiration_reminders']
   
   iaas:
      image: cloudcix/iaas:latest
      container_name: iaas
      environment:
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - POD_NAME=${POD_NAME}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - SENTRY_URL=${COP_SENTRY_URL}
         - PAM_NAME=${COP_PAM_NAME}
         - PAM_ORGANIZATION_URL=${COP_PAM_ORGANIZATION_URL}
         - SUPER_USER_IDS=${SUPER_USER_IDS}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_USER=${COP_EMAIL_USER}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - RELEASE=stable
      networks:
         cop:
         mgmt:
            ipv6_address: "${IP6}4004:3"
      volumes:
         - /home/administrator/.ssh/id_rsa.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
            
   appmanager:
      image: cloudcix/appmanager:latest
      container_name: appmanager
      environment:
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - POD_NAME=${POD_NAME}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - SENTRY_URL=${COP_SENTRY_URL}
         - PAM_NAME=${COP_PAM_NAME}
         - PAM_ORGANIZATION_URL=${COP_PAM_ORGANIZATION_URL}
         - SUPER_USER_IDS=${SUPER_USER_IDS}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_USER=${COP_EMAIL_USER}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - RELEASE=stable
      networks:
         cop:
         mgmt:
            ipv6_address: "${IP6}4004:4"
      volumes:
         - /home/administrator/.ssh/id_rsa.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   cop:
      image: cloudcix/cop:latest
      container_name: cop
      environment:
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - POD_NAME=${POD_NAME}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - SENTRY_URL=${COP_SENTRY_URL}
         - PAM_NAME=${COP_PAM_NAME}
         - PAM_ORGANIZATION_URL=${COP_PAM_ORGANIZATION_URL}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_USER=${COP_EMAIL_USER}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
      networks:
         cop:
         mgmt:
            ipv6_address: "${IP6}5002:3"
      ports:
         - "${PMS5}:80:80"
         - "${PMS5}:443:443"
      volumes:
         - /home/administrator/.ssh/id_rsa.pub:/app_framework/system_conf/public-key.rsa
   
   apache:
      image: cloudcix/apiproxy:latest
      container_name: apiproxy
      networks:
         cop:
      environment:
         - ADMIN_EMAIL=${LETS_ENCRYPT_ADMIN_EMAIL}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - POD_NAME=${POD_NAME}
      ports:
         - "${PMS4}:80:80"
         - "${PMS4}:443:443"
      volumes:
         - type: volume
           source: letsencrypt
           target: /etc/letsencrypt
           volume: 
              nocopy: true
      
   apachedscop:
      image: tgbyte/apacheds:latest
      container_name: apachedscop
      networks:
         cop:
         mgmt:
            ipv6_address: "${IP6}5002:2"
         
   pgadmincop:
      image: dpage/pgadmin4
      container_name: pgadmincop
      networks:
         cop:
         mgmt:
            ipv6_address: "${IP6}5002:1"
      ports:
         - "${PMS5}:5432:80"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMINCOP_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMINCOP_PASSWORD}
      depends_on:
         - pgsqlapi
         - pgsqltotp
 
   seed_pgsql:
      image: cloudcix/seed:latest
      container_name: seed_pgsql
      networks:
         cop:
      environment:
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - POD_NAME=${POD_NAME}
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
      restart: on-failure
      depends_on:
         - pgsqlapi
         - membership
         - membershipldap
         - appmanager
         - iaas
         - otp

volumes:
# cop volumes
   letsencrypt:
