networks:
  mgmt:
    driver: bridge
    enable_ipv6: true
    attachable: true
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv6: "routed"
    ipam:
      config:
        - subnet: "${DOCKER_MGMT_IP6}/64"
          gateway: "${DOCKER_MGMT_IP6}1"

volumes:
  # cop volumes
  cop_static_content:
  legacyapi_media_content:
  legacyapi_private_media_content:
  legacyapi_static_content:

x-common-env: &common-env
  CLOUDCIX_API_KEY: ${CLOUDCIX_API_KEY}
  CLOUDCIX_API_PASSWORD: ${CLOUDCIX_API_PASSWORD}
  CLOUDCIX_API_USERNAME: ${CLOUDCIX_API_USERNAME}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_PASSWORD: ${EMAIL_PASSWORD}
  EMAIL_PORT: ${EMAIL_PORT}
  EMAIL_USER: ${EMAIL_USER}
  LOGSTASH_ENABLE: ${LOGSTASH_ENABLE}
  LOGSTASH_URL: ${LOGSTASH_URL}
  ORGANIZATION_URL: ${ORGANIZATION_URL}
  PAT_NAME: ${PAT_NAME}
  PAT_ORGANIZATION_URL: ${PAT_ORGANIZATION_URL}
  PGSQLAPI_PASSWORD: ${PGSQLAPI_PASSWORD}
  PGSQLAPI_USER: ${PGSQLAPI_USER}
  POD_NAME: ${POD_NAME}
  POD_SECRET_KEY: ${POD_SECRET_KEY}
  PORTAL_NAME: ${PORTAL_NAME}
  RELEASE: stable

x-base-service: &base-service
  mem_limit: 4g
  restart: unless-stopped

x-api-base: &api-base
  <<: *base-service
  depends_on:
    - pgsqlapi

x-ssh-pub: &ssh-pub  /home/administrator/.ssh/id_rsa.pub:/application_framework/public-key.rsa

x-common-robot-env: &common-robot-env
  CLOUDCIX_LOCK_CREDENTIALS: ${CLOUDCIX_LOCK_CREDENTIALS}
  CLOUDCIX_LOCK_USER: ${CLOUDCIX_LOCK_USER}
  COP_NAME: ${COP_NAME}
  COP_ORGANIZATION_URL: ${COP_ORGANIZATION_URL}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_PASSWORD: ${EMAIL_PASSWORD}
  EMAIL_PORT: ${EMAIL_PORT}
  EMAIL_USER: ${EMAIL_USER}
  LOGSTASH_ENABLE: ${LOGSTASH_ENABLE}
  LOGSTASH_URL: ${LOGSTASH_URL}
  PAT_NAME: ${PAT_NAME}
  PAT_ORGANIZATION_URL: ${PAT_ORGANIZATION_URL}
  POD_NAME: ${POD_NAME}
  PORTAL_NAME: ${PORTAL_NAME}
  ORGANIZATION_URL: ${ORGANIZATION_URL}
  ROBOT_API_KEY: ${ROBOT_API_KEY}
  ROBOT_API_PASSWORD: ${ROBOT_API_PASSWORD}
  ROBOT_API_USERNAME: ${ROBOT_API_USERNAME}
  SEND_TO_FAIL: ${EMAIL_REPLY_TO}

x-robot-base: &robot-base
  <<: *base-service
  image: cloudcix/robot:5
  environment: *common-robot-env
  depends_on:
    - pgsqllocks

x-common-routine-env: &common-routine-env
  CLOUDCIX_API_KEY: ${CLOUDCIX_API_KEY}
  CLOUDCIX_API_PASSWORD: ${CLOUDCIX_API_PASSWORD}
  CLOUDCIX_API_USERNAME: ${CLOUDCIX_API_USERNAME}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_PASSWORD: ${EMAIL_PASSWORD}
  EMAIL_PORT: ${EMAIL_PORT}
  EMAIL_REPLY_TO: ${EMAIL_REPLY_TO}
  EMAIL_USER: ${EMAIL_USER}
  LOGSTASH_ENABLE: ${LOGSTASH_ENABLE}
  LOGSTASH_URL: ${LOGSTASH_URL}
  ORGANIZATION_URL: ${ORGANIZATION_URL}
  POD_NAME: ${POD_NAME}
  PORTAL_NAME: ${PORTAL_NAME}

x-routine-base: &routine-base
  <<: *api-base
  image: cloudcix/routine:3
  environment: *common-routine-env

services:
  # common
  jaeger:
    <<: *base-service
    image: jaegertracing/jaeger-agent:latest
    container_name: jaeger-agent
    command: ["--reporter.grpc.host-port=${JAEGER_URL}:14250"]
    networks:
      mgmt:

  pgadmin:
    <<: *base-service
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}5002:1"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - /data/pgadmin/backup:/data/backup

  # cop
  apachedscop:
    image: tgbyte/apacheds:latest
    container_name: apachedscop
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}5002:2"

  appmanager:
    <<: *api-base
    image: cloudcix/appmanager:5
    container_name: appmanager
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:4"
    volumes:
      - *ssh-pub  

  circuit:
    <<: *api-base
    image: cloudcix/circuit:5
    container_name: circuit
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:11"
    volumes:
      - *ssh-pub

  contact:
    <<: *api-base
    image: cloudcix/contact:5
    container_name: contact
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:15"
    volumes:
      - *ssh-pub

  cop:
    <<: *api-base
    image: cloudcix/cop:5
    container_name: cop
    environment:
      <<: *common-env
      POD_ID: ${POD_ID}
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}5002:4"
    volumes:
      - /home/administrator/.saml_certs:/app_framework/system_conf/saml_certs
      - cop_static_content:/static
      - /home/administrator/.ssh/id_rsa.pub:/app_framework/system_conf/public-key.rsa

  copmemcached:
    <<: *base-service
    image: memcached:latest
    container_name: copmemcached
    command: memcached -I 5m
    networks:
      mgmt:

  financial:
    <<: *api-base
    image: cloudcix/financial:5
    container_name: financial
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:6"
    environment:
      <<: *common-env
    volumes:
      - *ssh-pub
    
  flowerroutine:
    <<: *base-service
    image: mher/flower:0.9.5
    container_name: flowerroutine
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}5002:3"
    entrypoint: flower --port=5555 --broker=amqp://rabbitmqroutine:5672/

  helpdesk:
    <<: *api-base
    image: cloudcix/helpdesk:5
    container_name: helpdesk
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:18"
    volumes:
      - *ssh-pub

  iaas:
    <<: *api-base
    image: cloudcix/iaas:5
    container_name: iaas
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:3"
    environment:
      <<: *common-env
    volumes:
      - *ssh-pub
  
  legacyapi:
    <<: *api-base
    image: cloudcix/legacyapi:4
    container_name: legacyapi
    environment:
      <<: *common-env
    networks:
      mgmt:
       ipv6_address: "${DOCKER_MGMT_IP6}4004:12"
    volumes:
      - legacyapi_media_content:/media
      - legacyapi_private_media_content:/private_media
      - legacyapi_static_content:/static
      - *ssh-pub

  membership:
    <<: *api-base
    image: cloudcix/membership:5
    container_name: membership
    environment:
      <<: *common-env
      MEMBERSHIPLDAP_DC: ${MEMBERSHIPLDAP_DC}
      MEMBERSHIPLDAP_PASSWORD: ${MEMBERSHIPLDAP_PASSWORD}
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:1"
    volumes:
      - /home/administrator/.ssh/id_rsa:/application_framework/private-key.rsa
      - *ssh-pub
    depends_on:
      - pgsqlapi
      - membershipldap

  membershipldap:
    image: osixia/openldap
    container_name: membershipldap
    networks:
      mgmt:
    environment:
      - LDAP_ADMIN_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
      - LDAP_DOMAIN=${ORGANIZATION_URL}
      - LDAP_ORGANISATION=${ORGANIZATION_URL}
      - LDAP_TLS=false
    volumes:
      - /data/slapd/membershipldap/database:/var/lib/ldap
      - /data/slapd/membershipldap/config:/etc/ldap/slapd.d

  membershipldapbackup:
    image: osixia/openldap-backup
    container_name: membershipldapbackup
    networks:
      mgmt:
    environment:
      - LDAP_BACKUP_CONFIG_CRON_EXP="0 4 * * *"
      - LDAP_BACKUP_DATA_CRON_EXP="0 4 * * *"
    volumes_from:
      - membershipldap
    volumes:
      - /data/openldap/membershipldap/backup:/data/backup

  nginx1:
    <<: *base-service
    image: nginx:1.19.2-alpine
    container_name: nginx1
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:a"
    environment:
      - ORGANIZATION_URL=${ORGANIZATION_URL}
      - POD_NAME=${POD_NAME}
    ports:
      - "${PMS4}:443:443"
    volumes:
      - ./templates/nginx1:/etc/nginx/templates
      - /etc/nginx/certs:/etc/nginx/certs
    depends_on:
      - appmanager
      - circuit
      - compute
      - contact
      - financial
      - helpdesk
      - iaas
      - membership
      - otp
      - pat
      - plot
      - scheduler
      - support
      - training

  nginx2:
    <<: *base-service
    image: nginx:1.19.2-alpine
    container_name: nginx2
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4005:a"
    environment:
      - ORGANIZATION_URL=${ORGANIZATION_URL}
      - POD_NAME=${POD_NAME}
      - PORTAL_NAME=${PORTAL_NAME}
    ports:
      - "${PMS5}:443:443"
    volumes:
      - ./templates/nginx2:/etc/nginx/templates
      - /etc/nginx/certs:/etc/nginx/certs
      - cop_static_content:/app_framework/static
      - leagacyapi_media_content:/application_framework/media
      - leagacyapi_private_media_content:/application_framework/private_media
      - leagacyapi_static_content:/application_framework/static
    depends_on:
      - cop
      - legacyapi

  otp:
    <<: *api-base
    image: cloudcix/otp:5
    container_name: otp
    environment:
      <<: *common-env
      PGSQLTOTP_PASSWORD: ${PGSQLTOTP_PASSWORD}
      PGSQLTOTP_USER: ${PGSQLTOTP_USER}
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:2"
    volumes:
      - *ssh-pub
    depends_on:
      - pgsqltotp

  pat:
    <<: *api-base
    image: cloudcix/pat:5.0
    container_name: pat
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:13"
    volumes:
      - *ssh-pub

  pgsqlapi:
    <<: *base-service
    image: cloudcix/pgsqlapi:5
    container_name: pgsqlapi
    networks:
      mgmt:
    environment:
      - POSTGRES_PASSWORD=${PGSQLAPI_PASSWORD}
      - POSTGRES_USER=${PGSQLAPI_USER}
    volumes:
      - /var/lib/pgsqlapi:/var/lib/postgresql/data/
      - ./backup/pgsqlapi:/data/backup
    
  pgsqltotp:
    <<: *base-service
    image: cloudcix/pgsqltotp:5
    container_name: pgsqltotp
    networks:
      mgmt:
    environment:
      - POSTGRES_PASSWORD=${PGSQLTOTP_PASSWORD}
      - POSTGRES_USER=${PGSQLTOTP_USER}
    volumes:
      - /var/lib/pgsqltotp:/var/lib/postgresql/data/
      - ./backup/pgsqltotp:/data/backup

  plot:
    <<: *api-base
    image: cloudcix/plot:5
    container_name: plot
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:17"
    volumes:
      - *ssh-pub

  rabbitmqroutine:
    <<: *base-service
    image: rabbitmq
    container_name: rabbitmqroutine
    hostname: rabbitmqroutine
    networks:
      mgmt:

  routine:
    <<: *routine-base
    container_name: routine
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}5001:1"
    entrypoint: supervisord
    volumes:
      - /var/lib/routine/celerybeat:/opt/routine/celerybeat

  routineworker:
    <<: *routine-base
    container_name: routineworker
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}5001:2"
    entrypoint: celery -A celery_app -l info worker -Q celery -O fair -n ${POD_NAME} --concurrency 25

  scheduler:
    <<: *api-base
    image: cloudcix/scheduler:5
    container_name: scheduler
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:7"
    volumes:
      - *ssh-pub

  seed_pgsql:
    image: cloudcix/seed:3
    container_name: seed_pgsql
    networks:
      mgmt:
    environment:
      - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
      - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
      - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
      - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
      - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
      - ORGANIZATION_URL=${ORGANIZATION_URL}
      - PGSQLAPI_USER=${PGSQLAPI_USER}
      - PGSQLAPI_PASSWORD=${PGSQLAPI_PASSWORD}
      - POD_NAME=${POD_NAME}
      - POD_SECRET_KEY=${POD_SECRET_KEY}
      - PORTAL_NAME=${PORTAL_NAME}
    restart: on-failure
    depends_on:
      - appmanager
      - circuit
      - financial
      - iaas
      - legacyapi
      - membership
      - membershipldap
      - otp
      - pat
      - pgsqlapi
      - scheduler
      - support
      - training

  source_readings_cron:
    image: cloudcix/plotcron:5
    container_name: source_readings_cron
    environment:
      <<: *common-env
    networks:
      mgmt:
    command: ['source_readings_delete']
    volumes:
      - *ssh-pub

  support:
    <<: *api-base
    image: cloudcix/support:5
    container_name: support
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:10"
    volumes:
      - *ssh-pub

  training:
    <<: *api-base
    image: cloudcix/training:5
    container_name: training
    environment:
      <<: *common-env
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}4004:5"
    volumes:
      - *ssh-pub

  user_expiration_cron:
    image: cloudcix/membershipcron:5
    container_name: user_expiration_cron
    networks:
      mgmt:
    environment:
      <<: *common-env
      MEMBERSHIPLDAP_DC: ${MEMBERSHIPLDAP_DC}
      MEMBERSHIPLDAP_PASSWORD: ${MEMBERSHIPLDAP_PASSWORD}
    command: ['user_expiration_reminders']
    volumes:
      - /home/administrator/.ssh/id_rsa:/application_framework/private-key.rsa
      - *ssh-pub

  # region
  flowerrobot:
    <<: *base-service
    image: mher/flower:0.9.5
    container_name: flowerrobot
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6002:4"
    entrypoint: flower --port=5555 --broker=amqp://rabbitmq:5672/

  pgsqllocks:
    <<: *base-service
    image: cloudcix/pgsqllocks:5
    container_name: pgsqllocks
    networks:
      mgmt:
    environment:
      - POSTGRES_PASSWORD=${CLOUDCIX_LOCK_CREDENTIALS}
      - POSTGRES_USER=${CLOUDCIX_LOCK_USER}
    volumes:
      - /var/lib/pgsqllocks:/var/lib/postgresql/data/
      - ./backup/pgsqllocks:/data/backup

  rabbitmq:
    <<: *base-service
    image: rabbitmq
    container_name: rabbitmqrobot
    hostname: rabbitmq
    networks:
      mgmt:

  robot:
    <<: *robot-base
    container_name: robot
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6001:1"
    volumes:
      - /home/administrator/.ssh/id_rsa:/root/.ssh/id_rsa
      - /home/administrator/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /etc/cloudcix/pod/configs/config.json:/opt/robot/config.json
      - /var/lib/robot/celerybeat:/opt/robot/celerybeat
    entrypoint: supervisord

  robotworker:
    <<: *robot-base
    container_name: robotworker
    volumes:
      - /home/administrator/.ssh/id_rsa:/root/.ssh/id_rsa
      - /home/administrator/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /etc/cloudcix/pod/configs/config.json:/opt/robot/config.json
      - /etc/cloudcix/robot:/mnt/images
      - /etc/cloudcix/docker/.config/lxc:/root/.config/lxc
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6001:2"
    entrypoint: celery -A celery_app -l info worker -Q celery -O fair -n ${POD_NAME} --concurrency 25
