networks:
  mgmt:
    driver: bridge
    enable_ipv6: true
    attachable: true
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv6: "routed"
    ipam:
      config:
        - subnet: "${DOCKER_MGMT_IP6}/64"
          gateway: "${DOCKER_MGMT_IP6}1"

x-common-robot-env: &common-robot-env
  CLOUDCIX_LOCK_CREDENTIALS: ${CLOUDCIX_LOCK_CREDENTIALS}
  CLOUDCIX_LOCK_USER: ${CLOUDCIX_LOCK_USER}
  COP_NAME: ${COP_NAME}
  COP_ORGANIZATION_URL: ${COP_ORGANIZATION_URL}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_PASSWORD: ${EMAIL_PASSWORD}
  EMAIL_PORT: ${EMAIL_PORT}
  EMAIL_USER: ${EMAIL_USER}
  LOGSTASH_ENABLE: ${LOGSTASH_ENABLE}
  LOGSTASH_URL: ${LOGSTASH_URL}
  PAT_NAME: ${PAT_NAME}
  PAT_ORGANIZATION_URL: ${PAT_ORGANIZATION_URL}
  POD_NAME: ${POD_NAME}
  PORTAL_NAME: ${PORTAL_NAME}
  ORGANIZATION_URL: ${ORGANIZATION_URL}
  ROBOT_API_KEY: ${ROBOT_API_KEY}
  ROBOT_API_PASSWORD: ${ROBOT_API_PASSWORD}
  ROBOT_API_USERNAME: ${ROBOT_API_USERNAME}
  SEND_TO_FAIL: ${EMAIL_REPLY_TO}

x-base-service: &base-service
  mem_limit: 4g
  restart: unless-stopped

x-robot-base: &robot-base
  <<: *base-service
  image: cloudcix/robot:5
  environment: *common-robot-env
  depends_on:
    - pgsqllocks

services:
  # common
  jaeger:
    <<: *base-service
    image: jaegertracing/jaeger-agent:latest
    container_name: jaeger-agent
    command: ["--reporter.grpc.host-port=${JAEGER_URL}:14250"]
    networks:
      mgmt:
    restart: unless-stopped

  pgadmin:
    <<: *base-service
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}5002:1"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - /data/pgadmin/backup:/data/backup

  # region
  flowerrobot:
    <<: *base-service
    image: mher/flower:0.9.5
    container_name: flowerrobot
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6002:4"
    entrypoint: flower --port=5555 --broker=amqp://rabbitmq:5672/

  pgsqllocks:
    <<: *base-service
    image: cloudcix/pgsqllocks:5
    container_name: pgsqllocks
    networks:
      mgmt:
    environment:
      - POSTGRES_PASSWORD=${CLOUDCIX_LOCK_CREDENTIALS}
      - POSTGRES_USER=${CLOUDCIX_LOCK_USER}
    volumes:
      - /var/lib/pgsqllocks:/var/lib/postgresql/data/
      - ./backup/pgsqllocks:/data/backup

  rabbitmq:
    <<: *base-service
    image: rabbitmq
    container_name: rabbitmqrobot
    hostname: rabbitmq
    networks:
      mgmt:

  robot:
    <<: *robot-base
    container_name: robot
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6001:1"
    volumes:
      - /home/administrator/.ssh/id_rsa:/root/.ssh/id_rsa
      - /home/administrator/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /etc/cloudcix/pod/configs/config.json:/opt/robot/config.json
      - /var/lib/robot/celerybeat:/opt/robot/celerybeat
    entrypoint: supervisord

  robotworker:
    <<: *robot-base
    container_name: robotworker
    volumes:
      - /home/administrator/.ssh/id_rsa:/root/.ssh/id_rsa
      - /home/administrator/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /etc/cloudcix/pod/configs/config.json:/opt/robot/config.json
      - /etc/cloudcix/robot:/mnt/images
      - /etc/cloudcix/docker/.config/lxc:/root/.config/lxc
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6001:2"
    entrypoint: celery -A celery_app -l info worker -Q celery -O fair -n ${POD_NAME} --concurrency 25
