version: '3'

networks:
  mgmt:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "${DOCKER_MGMT_IP6}/64"
          gateway: "${DOCKER_MGMT_IP6}1"

services:
  # common
  jaeger:
    image: jaegertracing/jaeger-agent:latest
    container_name: jaeger-agent
    command: ["--reporter.grpc.host-port=${JAEGER_URL}:14250"]
    networks:
      mgmt:
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}5002:1"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - /data/pgadmin/backup:/data/backup

  # region
  flowerrobot:
    image: mher/flower:0.9.5
    container_name: flowerrobot
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6002:4"
    entrypoint: flower --port=5555 --broker=amqp://rabbitmqrobot:5672/

  pgsqllocks:
    image: cloudcix/pgsqllocks:${CLOUDCIX_VERSION}
    container_name: pgsqllocks
    networks:
      mgmt:
    environment:
      - POSTGRES_PASSWORD=${CLOUDCIX_LOCK_CREDENTIALS}
      - POSTGRES_USER=${CLOUDCIX_LOCK_USER}
    volumes:
      - /var/lib/pgsqllocks:/var/lib/postgresql/data/
      - ./backup/pgsqllocks:/data/backup

  rabbitmqrobot:
    image: rabbitmq
    container_name: rabbitmqrobot
    hostname: rabbitmq
    # hostname: rabbitmqrobot
    networks:
      mgmt:

  robot:
    image: cloudcix/robot:${CLOUDCIX_VERSION}
    container_name: robot
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6001:1"
    environment:
      - CLOUDCIX_LOCK_CREDENTIALS=${CLOUDCIX_LOCK_CREDENTIALS}
      - CLOUDCIX_LOCK_USER=${CLOUDCIX_LOCK_USER}
      - COP_NAME=${COP_NAME}
      - COP_ORGANIZATION_URL=${COP_ORGANIZATION_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - PAT_NAME=${PAT_NAME}
      - PAT_ORGANIZATION_URL=${PAT_ORGANIZATION_URL}
      - POD_NAME=${POD_NAME}
      - PORTAL_NAME=${PORTAL_NAME}
      - ORGANIZATION_URL=${ORGANIZATION_URL}
      - ROBOT_API_KEY=${ROBOT_API_KEY}
      - ROBOT_API_PASSWORD=${ROBOT_API_PASSWORD}
      - ROBOT_API_USERNAME=${ROBOT_API_USERNAME}
      - SEND_TO_FAIL=${EMAIL_REPLY_TO}
      # to be deprecated
      - CEPH_MONITORS=${CEPH_MONITORS}
      - COP_PORTAL=${PORTAL_NAME}
      - NETWORK_PASSWORD=${NETWORK_PASSWORD}
      - PAM_NAME=${PAT_NAME}
      - PAM_ORGANIZATION_URL=${PAT_ORGANIZATION_URL}
      - PODNET_CPE=${PODNET_CPE}
      - ROUTER_PRIVATE_INTERFACE=${ROUTER_PRIVATE_INTERFACE}
      - ROUTER_PUBLIC_INTERFACE=${ROUTER_PUBLIC_INTERFACE}
      - ROUTER_MGMT_IP=${ROUTER_MANAGEMENT_IP}
    volumes:
      - /var/lib/robot/celerybeat:/opt/robot/celerybeat
      - /home/administrator/.ssh/id_rsa:/root/.ssh/id_rsa
      - /home/administrator/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    entrypoint: supervisord
    depends_on:
      - pgsqllocks

  robotworker:
    image: cloudcix/robot:${CLOUDCIX_VERSION}
    container_name: robotworker
    environment:
      - CLOUDCIX_LOCK_CREDENTIALS=${CLOUDCIX_LOCK_CREDENTIALS}
      - CLOUDCIX_LOCK_USER=${CLOUDCIX_LOCK_USER}
      - COP_NAME=${COP_NAME}
      - COP_ORGANIZATION_URL=${COP_ORGANIZATION_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - PAT_NAME=${PAT_NAME}
      - PAT_ORGANIZATION_URL=${PAT_ORGANIZATION_URL}
      - POD_NAME=${POD_NAME}
      - PORTAL_NAME=${PORTAL_NAME}
      - ORGANIZATION_URL=${ORGANIZATION_URL}
      - ROBOT_API_KEY=${ROBOT_API_KEY}
      - ROBOT_API_PASSWORD=${ROBOT_API_PASSWORD}
      - ROBOT_API_USERNAME=${ROBOT_API_USERNAME}
      - SEND_TO_FAIL=${EMAIL_REPLY_TO}
      # to be deprecated
      - CEPH_MONITORS=${CEPH_MONITORS}
      - COP_PORTAL=${PORTAL_NAME}
      - NETWORK_PASSWORD=${NETWORK_PASSWORD}
      - PAM_NAME=${PAT_NAME}
      - PAM_ORGANIZATION_URL=${PAT_ORGANIZATION_URL}
      - PODNET_CPE=${PODNET_CPE}
      - ROUTER_PRIVATE_INTERFACE=${ROUTER_PRIVATE_INTERFACE}
      - ROUTER_PUBLIC_INTERFACE=${ROUTER_PUBLIC_INTERFACE}
      - ROUTER_MGMT_IP=${ROUTER_MANAGEMENT_IP}
    volumes:
      - /etc/cloudcix/robot:/mnt/images
      - /home/administrator/.ssh/id_rsa:/root/.ssh/id_rsa
      - /home/administrator/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    networks:
      mgmt:
        ipv6_address: "${DOCKER_MGMT_IP6}6001:2"
    entrypoint: celery -A celery_app -l info worker -Q celery -O fair -n ${POD_NAME} --concurrency 25
    depends_on:
      - pgsqllocks
