version: '3'

services:
  robot:
    image: cloudcix/robot:0.1
    container_name: robot
    environment:
       - NETWORK_PASSWORD=${NETWORK_PASSWORD}
       - COP_NAME=${COP_NAME}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION=${ORGANIZATION}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
    volumes:
       - /home/administrator/celerybeat:/opt/robot/celerybeat
    entrypoint: supervisord

  robotworker:
    image: cloudcix/robot:0.1
    container_name: robotworker
    environment:
       - NETWORK_PASSWORD=${NETWORK_PASSWORD}
       - COP_NAME=${COP_NAME}
       - POD_NAME=${POD_NAME}
       - ORGANIZATION=${ORGANIZATION}
       - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
       - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
       - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
    volumes:
      - /mnt:/mnt
    entrypoint: celery -A celery_app -l info worker -Q celery -O fair -n ${POD_NAME} --concurrency 25

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    
  flower:
    image: mher/flower:0.9.5
    container_name: flowerregion
    ports:
      - "${PMS6}:5555:5555"
      - "${IP6}6002:4:5555:5555"
    entrypoint: flower --port=5555 --broker=amqp://rabbitmq:5672/
