version: '3'
    
services:
   pgsqlpam:
     image: cloudcix/pgsqlpam:0.0
     container_name: pgsqlpam
     environment:
       - PGSQL_PASSWORD=${PGSQL_PASSWORD}
       - PGSQL_USER=${PGSQL_USER}
     volumes:
       - /var/lib/pgsqlpam:/var/lib/postgresql/data/
            
   pam:
     image: cloudcix/pam:0.4
     container_name: pam
     depends_on:
       - pgsqlpam
     environment:
       - PGSQL_PASSWORD=${PGSQL_PASSWORD}
       - PGSQL_USER=${PGSQL_USER}
       - POD_SECRET_KEY=${POD_SECRET_KEY}
     ports:
       - "10.${podid}.0.2:80:80"
       - "10.${podid}.0.2:443:80"
     restart: on-failure
     depends_on:
        - pgsqlpam

   mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_EMPTY_PW}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                
   librenms:
      image: librenms/librenms
      container_name: librenms
      ports:
         - "10.${podid}.0.4:80:80"
         - "10.${podid}.0.4:443:443"
         - "10.${podid}.0.4:161:161"
      depends_on:
         - mysql
      environment:
        - DB_HOST=mysql
        - DB_NAME=${MYSQL_DB}
        - DB_USER=${MYSQL_USER}
        - DB_PASSWORD=${MYSQL_PASSWORD}
   
   radius:
      image: freeradius/freeradius-server
      container_name: radius
      ports:
         - "10.${podid}.0.3:1645:1645"
         - "10.${podid}.0.3:1646:1646"

   ldap:
      image: osixia/openldap
      container_name: ldap
      ports:
         - "389:389"
      
   apacheds:
      image: tgbyte/apacheds:latest
      container_name: apacheds
      ports:
        - "${PMS3}:10389:10389"
        - "${IP6}3002:2:10389:10389"
      depends_on:
         - ldap

   pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      ports:
        - "${PMS3}:5432:80"
        - "${IP6}3002:1:5432:80"
      environment:
       - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
       - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      depends_on:
        - pgsqlpam

   jumphost:
      image: cloudcix/jumphost:latest
      container_name: jumphost
      ports:
        - "10.${podid}.0.5:22:22"
        - "10.${podid}.0.5:80:80"
        - "10.${podid}.0.5:5901:5901"
      entrypoint: tail -f /dev/null
