version: '3'

networks:
   pam:
      driver: bridge
   mgmt:
      driver: bridge
      enable_ipv6: true
      ipam:
         config:
            - subnet: "${IP6}/80"
              gateway: "${IP6}ffff"
   oob:
      driver: macvlan
      driver_opts:
         parent: ${OOB_INTERFACE}
      ipam:
         config:
            - subnet: "10.${pod_id}.0.0/16"
              ip_range: "10.${pod_id}.0.0/24"
              gateway: "10.${pod_id}.0.1"

services:
   pgsqlpam:
      image: cloudcix/pgsqlpam:latest
      container_name: pgsqlpam
      networks:
         pam:
      environment:
            - POSTGRES_PASSWORD=${PGSQLPAM_PASSWORD}
      volumes:
            - /var/lib/pgsqlpam:/var/lib/postgresql/data/


   pgadminpam:
      image: dpage/pgadmin4
      container_name: pgadminpam
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.7"
      ports:
         - "${PMS3}:5432:80"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMINPAM_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMINPAM_PASSWORD}
      depends_on:
         - pgsqlpam
                  
   pam:
      image: cloudcix/pam:latest
      container_name: pam
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.6"
      environment:
         - PGSQLPAM_PASSWORD=${PGSQLPAM_PASSWORD}
         - PGSQLPAM_USER=${PGSQLPAM_USER}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
      depends_on:
         - pgsqlpam
      restart: on-failure

   librenms:
      image: librenms/librenms
      container_name: librenms
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.4"
      environment:
         - DB_HOST=mysql
         - DB_NAME=${MYSQL_DATABASE}
         - DB_USER=${MYSQL_USER}
         - DB_PASSWORD=${MYSQL_PASSWORD}
      depends_on:
         - mysql

   mysql:
      image: mysql
      container_name: mysql
      networks:
         pam:
      ports:
         - "3306:3306"
      environment:
         - MYSQL_DATABASE=${MYSQL_DATABASE}
         - MYSQL_USER=${MYSQL_USER}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
         - "/etc/cloudcix/docker/radius/data:/var/lib/mysql"
         - "/etc/cloudcix/docker/radius/radius.sql:/docker-entrypoint-initdb.d/radius.sql"
      command: --default-authentication-plugin=mysql_native_password
      restart: always


   radius:
      image: 2stacks/freeradius
      container_name: radius
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.3"
      ports:
         - "1812-1813:1812-1813/udp"
      environment:
         - DB_NAME=${MYSQL_DATABASE}
         - DB_HOST=mysql
         - DB_USER=${MYSQL_USER}
         - DB_PASS=${MYSQL_PASSWORD}
         - RADIUS_KEY=${RADIUS_SECRET_KEY}
         - RAD_CLIENTS=10.0.0.0/8
      depends_on:
         - mysql
      links:
         - mysql
      restart: always

   mysql-workbench:
      image: ghcr.io/linuxserver/mysql-workbench
      container_name: mysql-workbench
      networks:
         pam:
         oob:
            ipv4_address: "10.${pod_id}.0.8"
      ports:
         - 3000:3000
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/Dublin
      cap_add:
         - IPC_LOCK
      restart: unless-stopped

   jumphost:
      image: cloudcix/jumphost:latest
      container_name: jumphost
      networks:
         oob:
            ipv4_address: "10.${pod_id}.0.5"
         mgmt:
            ipv6_address: "${IP6}3002:1"
      environment:
         - RESOLUTION=1280x720
         - USER=${JUMPHOST_USERNAME}
         - PASSWORD=${JUMPHOST_PASSWORD}
         - HTTP_PASSWORD=${JUMPHOST_HTTP_PASSWORD}
         - VNC_PASSWORD=${JUMPHOST_VNC_PASSWORD}
      restart: always